services:
  mongo-dev:
    image: 'mongo:latest'
    container_name: mongo-dev
    # volumes:
    #   - './data/db:/data/db'
    ports:
      - 27017:27017
  parse-dev:
    image: 'parseplatform/parse-server:latest'
    environment:
      - PARSE_SERVER_APPLICATION_ID=APPLICATION_ID
      - PARSE_SERVER_MASTER_KEY=MASTER_KEY
      - PARSE_SERVER_DATABASE_URI=mongodb://mongo-dev:27017/parse
      # - PARSE_SERVER_MOUNT_PATH=/parse
    ports:
      - '1337:1337'
    links:
      - mongo-dev
  parse-dashboard:
    image: 'parseplatform/parse-dashboard:latest'
    ports:
      - '4040:4040'
    environment:
      - PARSE_DASHBOARD_ALLOW_INSECURE_HTTP=true
      - PARSE_DASHBOARD_SERVER_URL=/api
      - PARSE_DASHBOARD_MASTER_KEY=MASTER_KEY
      - PARSE_DASHBOARD_APP_ID=APPLICATION_ID
      - PARSE_DASHBOARD_APP_NAME=TodoListAppDev
      - PARSE_DASHBOARD_USER_ID=admin
      - PARSE_DASHBOARD_USER_PASSWORD=ADMIN_PASSWORD
      # - MOUNT_PATH=/dashboard/
    