services:
  server:
    build:
      context: ./node.js
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 5000:5000
  db:
    build:
      context: ./db
      dockerfile: ./Dockerfile
    ports:
      - 1521:1521
    volumes:
      - ./db/data:/opt/h2-data
  client-builder:
    build:
      context: ./client
      dockerfile: ./Dockerfile
    volumes:
      - ./client/release_outputs:/app/release_outputs